server:
    port: 8081


mybatis:
    mapperConfig: classpath:mapper/*.xml
    type-aliases-package: com.yuanwj.demo.model
spring:
    datasource:
        username: root
        password: 123456
        url: jdbc:mysql://localhost:3306/edb_a20000?seSSL=false
#      driver-class-name: